'use strict';
// Deterministic, dependency-free analysis; no semantic material recognition.
const CuevaAlgo={
 version:'cueva-local-1.0',
 quality(data,w,h){let sum=0,sum2=0,dark=0,bright=0,edge=0;const gray=new Float32Array(w*h);for(let i=0;i<gray.length;i++){const y=.2126*data[i*4]+.7152*data[i*4+1]+.0722*data[i*4+2];gray[i]=y;sum+=y;sum2+=y*y;dark+=y<12;bright+=y>243}for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=y*w+x,v=4*gray[i]-gray[i-1]-gray[i+1]-gray[i-w]-gray[i+w];edge+=v*v}const mean=sum/gray.length;return{mean,contrast:Math.sqrt(Math.max(0,sum2/gray.length-mean*mean)),darkFraction:dark/gray.length,brightFraction:bright/gray.length,laplacianVariance:edge/Math.max(1,(w-2)*(h-2)),gray}},
 otsu(gray){const hist=new Uint32Array(256);for(const v of gray)hist[Math.round(v)]++;let sum=0,wb=0,sb=0,best=-1,t=0;for(let i=0;i<256;i++)sum+=i*hist[i];for(let i=0;i<256;i++){wb+=hist[i];if(!wb)continue;const wf=gray.length-wb;if(!wf)break;sb+=i*hist[i];const variance=wb*wf*(sb/wb-(sum-sb)/wf)**2;if(variance>best){best=variance;t=i}}return t},
 components(mask,w,h,minArea=40){const seen=new Uint8Array(mask.length),queue=new Int32Array(mask.length),out=[];for(let start=0;start<mask.length;start++){if(!mask[start]||seen[start])continue;let head=0,tail=1,minX=w,minY=h,maxX=0,maxY=0;queue[0]=start;seen[start]=1;while(head<tail){const i=queue[head++],x=i%w,y=Math.floor(i/w);minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);const near=[];if(x)near.push(i-1);if(x<w-1)near.push(i+1);if(y)near.push(i-w);if(y<h-1)near.push(i+w);for(const n of near)if(mask[n]&&!seen[n]){seen[n]=1;queue[tail++]=n}}if(tail>=minArea)out.push({area:tail,box:[minX,minY,maxX-minX+1,maxY-minY+1]})}return out.sort((a,b)=>b.area-a.area)},
 lab(r,g,b){const linear=v=>{v/=255;return v>.04045?((v+.055)/1.055)**2.4:v/12.92};r=linear(r);g=linear(g);b=linear(b);const f=t=>t>.008856?Math.cbrt(t):7.787*t+16/116;const x=f((.4124*r+.3576*g+.1805*b)/.95047),y=f(.2126*r+.7152*g+.0722*b),z=f((.0193*r+.1192*g+.9505*b)/1.08883);return[116*y-16,500*(x-y),200*(y-z)]},
 cluster(data,k=4){const n=data.length/4,lab=new Float32Array(n*3);for(let i=0;i<n;i++)lab.set(this.lab(...data.slice(i*4,i*4+3)),i*3);let centers=Array.from({length:k},(_,j)=>Array.from(lab.slice(Math.floor((j+.5)*n/k)*3,Math.floor((j+.5)*n/k)*3+3)));const labels=new Uint8Array(n),counts=new Uint32Array(k);for(let it=0;it<6;it++){const sums=Array.from({length:k},()=>[0,0,0,0]);for(let i=0;i<n;i++){let best=0,dist=Infinity;for(let j=0;j<k;j++){let d=0;for(let c=0;c<3;c++)d+=(lab[i*3+c]-centers[j][c])**2;if(d<dist){dist=d;best=j}}labels[i]=best;for(let c=0;c<3;c++)sums[best][c]+=lab[i*3+c];sums[best][3]++}centers=centers.map((old,j)=>sums[j][3]?sums[j].slice(0,3).map(v=>v/sums[j][3]):old)}for(const j of labels)counts[j]++;return{labels,counts,centers}},
 rle(labels){const out=[];let last=labels[0],n=0;for(const v of labels){if(v===last)n++;else{out.push(last,n);last=v;n=1}}if(n)out.push(last,n);return out},
 process(state,now,settings){const cfg={threshold:80,leadHours:24,...settings},active=state.lots.filter(l=>!['Cerrado'].includes(l.status)&&l.process==='En obra');return active.map(l=>{const alerts=state.v2.alerts.filter(a=>a.unit===l.id&&a.status!=='Resuelta'),ops=state.v2.operations.filter(o=>o.unit===l.id&&o.lotId===l.lotId&&o.type==='Vertido manual'&&/^kg/.test(o.measure)&&Number.isFinite(Date.parse(o.time))).sort((a,b)=>Date.parse(a.time)-Date.parse(b.time));const span=ops.length>1?(Date.parse(ops.at(-1).time)-Date.parse(ops[0].time))/3600000:0;const rate=span>=1?ops.slice(1).reduce((s,o)=>s+Number(o.amount||0),0)/span:null;const fill=Math.max(0,Math.min(100,Number(l.fill)||0));const blocked=alerts.length>0||l.status==='Cuarentena'||l.status==='Revisión';const age=Math.max(0,(now-Date.parse(l.date))/86400000)||0;const score=Math.round((blocked?100:0)+fill+Math.min(age,30));const reasons=[...(blocked?[alerts.length?'Resolver '+alerts.length+' incidencias antes de planificar':'Revisar estado '+l.status+' antes de planificar']:[]),...(fill>=cfg.threshold?['Ocupación declarada ≥ '+cfg.threshold+' %']:[]),...(age>=14?['Acopio de '+Math.floor(age)+' días; revisar retirada']:[])];const capacity=fill>0?l.kg*100/fill:null;const hours=rate&&capacity?Math.max(0,(capacity-l.kg)/rate):null;if(hours!==null&&hours<=cfg.leadHours)reasons.push('Proyección orientativa dentro de '+cfg.leadHours+' h');return{unit:l.id,lotId:l.lotId,work:l.work,manager:l.manager,code:l.code,score,blocked,fill,age,rate,hours,reasons,eligible:!blocked&&(fill>=cfg.threshold||(hours!==null&&hours<=cfg.leadHours)),method:'Heurística explicable; ocupación declarada y vertidos del lote, sin optimización de ruta'}}).sort((a,b)=>b.score-a.score)},
 groups(recs){const groups={};for(const r of recs.filter(r=>r.eligible)){const key=[r.work,r.manager,r.code].join('|');(groups[key]??={work:r.work,manager:r.manager,code:r.code,units:[]}).units.push(r.unit)}return Object.values(groups)}
};
