'use strict';
const localDeposit=deposit;
deposit=function(id){localDeposit(id);const actions=$('.capture-area .actions');actions?.insertAdjacentHTML('beforeend',`<button type="button" data-local="screen">Compartir ventana TeamViewer</button>`)};
async function shareWindow(){try{stopCapture();captureStream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});const v=$('#capture-video');v.srcObject=captureStream;v.hidden=false;$('#capture-status').textContent='Ventana compartida · toma foto o graba vídeo';const note=$('#v2-deposit [name="note"]');if(note)note.value='Captura de ventana remota (pantalla), no imagen original de cámara. '+note.value;captureStream.getVideoTracks()[0].addEventListener('ended',()=>{if($('#capture-status'))$('#capture-status').textContent='La pantalla ha dejado de compartirse'})}catch{toast('No se ha compartido la ventana. Selecciónala en el diálogo del navegador o usa una foto.')}}
const localVision=vision;
vision=function(){return `<div class="agent-strip"><span>PRUEBA LOCAL · webcam o ventana de TeamViewer</span><button data-local="vision-capture">Capturar para análisis</button></div>`+localVision()};
function visionCapture(){captureBlob=null;modal('Captura local / ventana remota',`<p>Para TeamViewer, conecta primero con el equipo y abre allí la vista de la cámara. Selecciona después esa ventana en el diálogo de compartir.</p><video id="capture-video" muted autoplay playsinline style="width:100%;max-height:380px;background:#122a41"></video><img id="capture-photo" hidden alt="Captura para analizar" style="width:100%"><p id="capture-status">Selecciona la fuente</p><div class="actions"><button data-v2="camera">Webcam de este ordenador</button><button data-local="screen">Ventana TeamViewer</button><button data-v2="snapshot">Tomar foto</button><button data-local="analyse-photo" class="primary">Usar foto en análisis</button></div><p>Compartir una ventana captura sus píxeles visibles; no obtiene el flujo original ni calibración de la cámara.</p>`)}
document.addEventListener('click',async e=>{const a=e.target.closest('[data-local]')?.dataset.local;if(a==='screen')await shareWindow();if(a==='vision-capture')visionCapture();if(a==='analyse-photo'){if(!captureBlob)return toast('Toma una fotografía primero.');const photo=captureBlob;closeModal();route='vision';location.hash='vision';render();await loadVision(photo)}});

render();
