'use strict';
const fieldViewport=()=>window.matchMedia('(max-width:1100px)').matches;
let fieldWork='';try{fieldWork=localStorage.getItem('cueva-field-work')||''}catch{}
let fieldTaskFilter='Pendientes',wizardIndex=0,wizardSteps=[];
const fieldBaseRender=render,fieldBaseDeposit=deposit;
nav.unshift(['EN OBRA','campo','Mi jornada','scan']);nav.push(['','jornada','Tareas de campo','board']);
function fieldUnits(){return state.lots.filter(l=>(!fieldWork||l.work===fieldWork)&&!['Cerrado'].includes(l.status))}
function fieldCard(l){const mat=mats.findIndex(m=>m[0]===l.code);return `<article class="field-unit"><button class="field-unit-open" data-unit="${esc(l.id)}"><span class="field-thumb ${mat<0?'generic':''}" ${mat>=0?`style="background-position:${mat%4*100/3}% ${Math.floor(mat/4)*50}%"`:''}>${mat<0?ico('box'):''}</span><span class="grow"><span class="between"><b>${esc(l.id)}</b>${badge(l.status)}</span><strong>${esc(ler(l.code).name)}</strong><small>${esc(l.zone)} · ${kg(l.kg)}</small></span></button><div class="field-unit-actions">${vbtn('Registrar operación','deposit:'+l.id,'primary')}${vbtn('Expediente','unit:'+l.id)}</div></article>`}
function fieldHome(){const lots=fieldUnits(),alerts=state.v2.alerts.filter(a=>a.status!=='Resuelta'&&lots.some(l=>l.id===a.unit)),pending=state.tasks.filter(t=>t.stage!=='Hecho'&&(!fieldWork||lots.some(l=>l.id===t.unit)));return `<div class="field-title"><div><span class="eyebrow">CUEVA / EN OBRA</span><h1>Mi jornada</h1><p>${new Date().toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long'})}</p></div><button data-action="scan" class="field-scan" aria-label="Leer QR o identificador">${ico('scan')}</button></div><label class="field-work"><span>Obra activa</span><select id="field-work"><option value="">Todas las obras</option>${works.map(w=>`<option value="${esc(w.id)}" ${fieldWork===w.id?'selected':''}>${esc(w.name)}</option>`).join('')}</select></label><div class="field-primary"><div><span class="eyebrow">REGISTRO EN EL PUNTO DE ACOPIO</span><h2>Identifica. Captura. Registra.</h2><p>Material, recipiente y evidencia unidos.</p></div><button data-v2="deposit" class="field-capture">${ico('camera')} Registrar vertido</button></div><div class="field-stats"><button data-action="nav:unidades"><b>${lots.length}</b><span>Unidades activas</span></button><button data-field="tasks"><b>${pending.length}</b><span>Tareas pendientes</span></button><button data-field="alerts"><b>${alerts.length}</b><span>Incidencias nuevas</span></button></div><div class="field-layout"><section><div class="field-section-title"><h2>A pie de obra</h2><button data-action="nav:unidades">Ver todas</button></div><div class="field-unit-list">${lots.slice(0,6).map(fieldCard).join('')||'<div class="empty">No hay unidades en esta obra.</div>'}</div></section><section><div class="field-section-title"><h2>Siguiente acción</h2><button data-field="tasks">Organizar</button></div>${pending.slice(0,4).map(fieldTask).join('')||'<div class="panel pad">Sin tareas pendientes en esta obra.</div>'}<div class="field-support"><h3>Consulta antes de actuar</h3><p>Compatibilidad, dudas de LER y procedimiento.</p><button data-v2="agent">${ico('shield')} Abrir asistente</button></div></section></div><p class="field-note">Datos iniciales de demostración. Los nuevos registros y evidencias se guardan en este navegador.</p>`}
function fieldTask(t){return `<article class="field-task"><div class="between"><span class="code">${esc(t.unit)}</span>${badge(t.priority)}</div><button class="field-task-title" data-v2="task:${t.id}">${esc(t.title)}</button><div class="between"><small>${esc(t.owner)} · ${esc(t.due)}</small><select data-task-stage="${t.id}" aria-label="Estado de ${esc(t.title)}">${['Por hacer','En curso','Bloqueado','Hecho'].map(s=>`<option ${s===t.stage?'selected':''}>${s}</option>`).join('')}</select></div></article>`}
function fieldTasks(){const lots=fieldUnits();const tasks=state.tasks.filter(t=>(fieldTaskFilter==='Todas'||(fieldTaskFilter==='Pendientes'?t.stage!=='Hecho':t.stage===fieldTaskFilter))&&(!fieldWork||lots.some(l=>l.id===t.unit)));return page('Tareas de campo','Acciones, responsables y plazos.',btn('Nueva tarea','newtask','primary','plus'))+`<div class="field-filter">${['Pendientes','En curso','Bloqueado','Hecho','Todas'].map(s=>`<button data-field-filter="${s}" class="${s===fieldTaskFilter?'active':''}">${s}</button>`).join('')}</div><div class="field-tasks-grid">${tasks.map(fieldTask).join('')||'<div class="empty">No hay tareas con este filtro.</div>'}</div>`}
function fieldMore(){modal('Todas las herramientas',`<div class="field-menu">${nav.map(n=>`<button data-field-route="${n[1]}">${ico(n[3])}<span>${n[2]}</span>${ico('arrow')}</button>`).join('')}</div>`)}
function fieldNav(){if(!$('#field-nav'))document.body.insertAdjacentHTML('beforeend',`<nav id="field-nav" class="field-bottom" aria-label="Navegación de campo"><button data-field-route="campo">${ico('dashboard')}<span>Hoy</span></button><button data-field-route="unidades">${ico('box')}<span>Unidades</span></button><button data-v2="deposit" class="field-nav-add" aria-label="Registrar vertido">${ico('plus')}</button><button data-field-route="jornada">${ico('board')}<span>Tareas</span></button><button data-field="more">${ico('layers')}<span>Más</span></button></nav>`);$$('#field-nav [data-field-route]').forEach(b=>b.classList.toggle('active',b.dataset.fieldRoute===route));document.body.classList.toggle('field-route',route==='campo'||route==='jornada')}
render=function(){if(['campo','jornada'].includes(route)){const current=route;route='control';fieldBaseRender();route=current;$('#main').innerHTML=current==='campo'?fieldHome():fieldTasks();$$('.navlink').forEach(a=>a.classList.toggle('active',a.hash==='#'+current));document.title=(current==='campo'?'Mi jornada':'Tareas de campo')+' · CUEVA'}else fieldBaseRender();fieldNav();if(fieldViewport()){$$('table').forEach(table=>{const labels=[...table.querySelectorAll('thead th')].map(h=>h.textContent);table.querySelectorAll('tbody tr').forEach(row=>[...row.children].forEach((cell,i)=>cell.dataset.label=labels[i]||''))})}}
function applyWizard(){const form=$('#v2-deposit');if(!form)return;$('#modal').classList.add('field-wizard');const groups=[...form.children];wizardSteps=[document.createElement('section'),document.createElement('section'),document.createElement('section'),document.createElement('section')];wizardSteps.forEach((s,i)=>{s.className='capture-step';s.dataset.captureStep=String(i)});for(const el of groups){let target=1;if(el.matches('.detailgrid'))target=el===groups[0]?0:1;else if(el.matches('.capture-area'))target=2;else if(el.matches('.notice,.checkline,.formerror,.actions'))target=3;wizardSteps[target].appendChild(el)}form.replaceChildren(...wizardSteps);const head=document.createElement('div');head.className='capture-progress';head.innerHTML=['Unidad','Residuo','Evidencia','Revisar'].map((s,i)=>`<button type="button" data-wizard-step="${i}"><span>${i+1}</span>${s}</button>`).join('');form.prepend(head);wizardSteps[3].insertAdjacentHTML('afterbegin','<div id="capture-summary" class="capture-summary"></div>');form.insertAdjacentHTML('beforeend','<div class="capture-navigation"><button type="button" data-wizard="back">Atrás</button><span id="capture-step-label"></span><button type="button" data-wizard="next" class="primary">Continuar →</button></div>');const assist=form.querySelector('[data-v2="agent"]');if(assist){assist.removeAttribute('data-v2');assist.dataset.field='compatibility-help'}wizardIndex=0;showWizard()}
function showWizard(){wizardSteps.forEach((s,i)=>s.hidden=i!==wizardIndex);$$('[data-wizard-step]').forEach((b,i)=>{b.classList.toggle('active',i===wizardIndex);b.setAttribute('aria-current',i===wizardIndex?'step':'false')});$('#capture-step-label').textContent=(wizardIndex+1)+' / 4';$('[data-wizard="back"]').disabled=wizardIndex===0;$('[data-wizard="next"]').hidden=wizardIndex===3;if(wizardIndex===3){const f=$('#v2-deposit'),d=Object.fromEntries(new FormData(f));$('#capture-summary').innerHTML=`<span class="eyebrow">ANTES DE GUARDAR</span><h3>${esc(d.unit)}</h3><dl><dt>Operación</dt><dd>${esc(d.type)}</dd><dt>Residuo</dt><dd>${esc(ler(d.code).name)} · ${code(d.code)}</dd><dt>Cantidad</dt><dd>${esc(d.amount||'Sin indicar')} ${esc(d.measure)}</dd><dt>Estado</dt><dd>${esc(d.condition)}</dd><dt>Evidencia</dt><dd>${captureBlob?'Captura preparada':$('#capture-file')?.files[0]?.name?'Archivo preparado':'Falta foto o vídeo'}</dd></dl>`}$('#modal-content').scrollTop=0}
function wizardMove(next){if(next>wizardIndex){const controls=[...wizardSteps[wizardIndex].querySelectorAll('input,select,textarea')];for(const c of controls)if(!c.checkValidity()){c.reportValidity();return}if(wizardIndex===2&&!captureBlob&&!$('#capture-file').files.length){toast('Toma una fotografía o adjunta una evidencia para continuar.');return}}wizardIndex=Math.max(0,Math.min(3,next));showWizard()}
deposit=function(id){fieldBaseDeposit(id);if(!id&&fieldWork){const lot=fieldUnits().find(l=>l.process==='En obra');if(lot){$('#deposit-unit').value=lot.id;$('#deposit-code').value=lot.code;selectedMat=lot.code;$('#mat-picker').innerHTML=matCards();compatibility()}}if(fieldViewport())applyWizard()};
document.addEventListener('click',e=>{const routeButton=e.target.closest('[data-field-route]');if(routeButton){if($('#modal').open)closeModal();go(routeButton.dataset.fieldRoute)}const b=e.target.closest('[data-field]');if(b){if(b.dataset.field==='compatibility-help'){const f=$('#v2-deposit'),d=Object.fromEntries(new FormData(f)),reply=agentReply(d.unit+' '+ler(d.code).name);let el=$('#capture-help');if(!el){el=document.createElement('div');el.id='capture-help';el.className='notice';$('#capture-summary').after(el)}el.textContent=reply.text;}if(b.dataset.field==='more')fieldMore();if(b.dataset.field==='tasks')go('jornada');if(b.dataset.field==='alerts')modal('Incidencias de campo',alertList())}const t=e.target.closest('[data-field-filter]');if(t){fieldTaskFilter=t.dataset.fieldFilter;render()}const step=e.target.closest('[data-wizard-step]');if(step){const target=+step.dataset.wizardStep;if(target>wizardIndex+1)toast('Completa el paso actual para continuar.');else wizardMove(target);}const move=e.target.closest('[data-wizard]');if(move)wizardMove(wizardIndex+(move.dataset.wizard==='next'?1:-1))});
document.addEventListener('change',e=>{if(e.target.id==='field-work'){fieldWork=e.target.value;try{localStorage.setItem('cueva-field-work',fieldWork)}catch{}render()}});
document.addEventListener('invalid',e=>{if(!e.target.closest('#v2-deposit')||!$('#modal').classList.contains('field-wizard'))return;const step=e.target.closest('[data-capture-step]');if(step&&step.hidden){wizardIndex=+step.dataset.captureStep;showWizard()}},true);
$('#modal').addEventListener('close',()=>$('#modal').classList.remove('field-wizard'));
if(!location.hash&&fieldViewport()){route='campo';location.hash='campo'}
render();
