'use strict';
// Autonomous browser persistence. No network requests, credentials or server.
const CuevaPrototype=(()=>{
 const dbName='cueva-wm-demo:'+new URL('.',location.href).pathname;
 const urls=new Map(),reverse=new Map();let ready;
 function db(){return ready??=new Promise((resolve,reject)=>{const r=indexedDB.open(dbName,1);r.onupgradeneeded=()=>{r.result.createObjectStore('records')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('Cierra las otras pestañas del prototipo y recarga'))})}
 async function transact(mode,action){const database=await db();return new Promise((resolve,reject)=>{const tx=database.transaction('records',mode);let output;tx.oncomplete=()=>resolve(output);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Operación cancelada'));try{action(tx.objectStore('records'),v=>output=v,tx)}catch(e){tx.abort();reject(e)}})}
 const get=key=>transact('readonly',(s,done)=>{const r=s.get(key);r.onsuccess=()=>done(r.result)});
 const put=(key,value)=>transact('readwrite',(s,done)=>{s.put(value,key);done(true)});
 const all=()=>transact('readonly',(s,done)=>{const out=[],r=s.openCursor();r.onsuccess=()=>{const c=r.result;if(c){out.push([c.key,c.value]);c.continue()}else done(out)}});
 const response=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json',...headers}});
 function mapTree(value,convert){if(typeof value==='string')return convert(value);if(Array.isArray(value))return value.map(v=>mapTree(v,convert));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,mapTree(v,convert)]));return value}
 function makeURL(key,blob){if(!urls.has(key)){const url=URL.createObjectURL(blob);urls.set(key,url);reverse.set(url,key)}return urls.get(key)}
 async function hydrate(value){for(const [key,entry]of await all())if(entry?.blob instanceof Blob)makeURL(key,entry.blob);return mapTree(value,s=>urls.get(s)||s)}
 const canonical=value=>mapTree(value,s=>reverse.get(s)||s);
 const hash=async blob=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()))).map(v=>v.toString(16).padStart(2,'0')).join('');
 async function request(path,options={}){try{const method=options.method||'GET';if(path==='state'&&method==='GET'){const current=await get('state');return response(current?await hydrate(current.data):null,200,current?{ETag:'"'+current.version+'"'}:{})}
 if(path==='state'&&method==='PUT'){const data=canonical(JSON.parse(options.body));if(!Array.isArray(data.lots)||!Array.isArray(data.tasks)||!data.v2||data.lots.some(l=>!Number.isFinite(l.kg)||l.kg<0))return response({error:'Datos inválidos'},400);const expected=new Headers(options.headers).get('If-Match');const result=await transact('readwrite',(s,done)=>{const r=s.get('state');r.onsuccess=()=>{const old=r.result,etag=old?'"'+old.version+'"':'new';if(etag!==expected){done(null);return}const next={data,version:(old?.version||0)+1};s.put(next,'state');done(next.version)}});return result?response({saved:true},200,{ETag:'"'+result+'"'}):response({error:'Hay un conflicto con otra pestaña. Exporta tu copia y recarga.'},409)}
 if((path==='media'||path==='analysis')&&method==='POST'){const type=new Headers(options.headers).get('Content-Type')||'',isAnalysis=path==='analysis',blob=new Blob([options.body],{type});if(blob.size>(isAnalysis?4:20)*1024*1024)return response({error:'Archivo demasiado grande'},413);if(!isAnalysis&&!['image/jpeg','image/png','image/webp','video/mp4','video/webm'].includes(type))return response({error:'Formato no admitido'},415);if(isAnalysis){const a=JSON.parse(await blob.text());if(typeof a.algorithm!=='string'||typeof a.version!=='string')return response({error:'Análisis sin algoritmo/versión'},400)}const id=crypto.randomUUID(),key='/api/'+path+'/'+id,sha256=await hash(blob);await put(key,{blob,sha256});return response({id,url:makeURL(key,blob),type,sha256,size:blob.size},201)}
 if(path.startsWith('media/')||path.startsWith('analysis/')){const v=await get('/api/'+path);return v?new Response(v.blob):response({error:'Archivo no disponible en este navegador'},404)}
 if(['agent','vision'].includes(path))return response({configured:false,mode:'local-demo'});
 if(['readings','manager-events','scale-events'].includes(path))return response([]);
 if(path==='contract')return response({mode:'Prototipo autónomo',storage:'IndexedDB en este navegador',network:'Sin API externa ni servidor',simulations:['tarjeta de empleado','básculas','RFID'],algorithms:'Reglas de proceso, Lab, Otsu, calidad y muestreo de vídeo locales'});
 return response({error:'Esta operación externa no forma parte de la demo autónoma'},400);
 }catch(e){return response({error:e.message||'No se pudo guardar en el navegador'},503)}}
 async function backup(){const records=[];for(const[key,v]of await all()){if(v?.blob instanceof Blob){const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(v.blob)});records.push({key,sha256:v.sha256,data})}else records.push({key,value:v})}return{format:'CUEVA_BROWSER_DEMO_1',createdAt:new Date().toISOString(),records}}
 async function restore(data){if(data?.format!=='CUEVA_BROWSER_DEMO_1'||!Array.isArray(data.records)||data.records.length>5000)throw Error('No es una copia completa CUEVA válida');const prepared=[],keys=new Set();for(const r of data.records){if(typeof r.key!=='string'||keys.has(r.key))throw Error('Claves repetidas o inválidas');keys.add(r.key);if(r.key==='state'){if(!r.value?.data?.v2||!Array.isArray(r.value.data.lots)||!Array.isArray(r.value.data.tasks)||r.value.data.lots.some(l=>!Number.isFinite(l.kg)||l.kg<0))throw Error('Estado inválido');prepared.push([r.key,{...r.value,version:Date.now()}])}else{if(!/^\/api\/(media|analysis)\/[a-f0-9-]{36}$/.test(r.key)||typeof r.data!=='string'||!/^data:(image\/(jpeg|png|webp)|video\/(mp4|webm)|application\/json);base64,/.test(r.data))throw Error('Evidencia inválida');const [prefix,encoded]=r.data.split(','),bytes=Uint8Array.from(atob(encoded),c=>c.charCodeAt(0)),blob=new Blob([bytes],{type:prefix.slice(5,-7)});if(blob.size>20*1024*1024||await hash(blob)!==r.sha256)throw Error('La huella de una evidencia no coincide');prepared.push([r.key,{blob,sha256:r.sha256}])}}if(!keys.has('state'))throw Error('La copia no contiene registros');await transact('readwrite',(s,done)=>{s.clear();for(const[key,v]of prepared)s.put(v,key);done(true)});for(const url of urls.values())URL.revokeObjectURL(url);urls.clear();reverse.clear()}
 return{request,backup,restore,dbName};
})();
