'use strict';
const protoButton=(t,a)=>`<button type="button" data-proto="${a}">${t}</button>`;
about=function(){modal('CUEVA · demo autónoma',`<h2>Todo el prototipo en tu navegador.</h2><p>Sin servidor, cuentas API ni conectores. Los registros, fotografías, vídeos y configuraciones se guardan en este navegador y en esta dirección.</p><div class="notice">La tarjeta y las básculas son simulaciones. El asistente usa reglas locales. Los algoritmos de imagen y vídeo se ejecutan sobre los archivos que aportas; no incluyen un modelo semántico de materiales.</div><div class="actions">${protoButton('Descargar copia completa','backup')}</div><h3>Restaurar copia</h3><p>Reemplaza los datos de esta demo en el navegador. Exporta primero si quieres conservarlos.</p><input id="proto-restore-file" type="file" accept="application/json,.json"><label class="checkline"><input id="proto-restore-confirm" type="checkbox"> Confirmo reemplazar los registros y evidencias de este navegador</label>${protoButton('Restaurar copia seleccionada','restore')}<p><a href="LEEME.html" target="_blank" rel="noopener">Guía para GitHub y uso ↗</a></p>`)};$('#about').onclick=about;
connectorView=function(){return page('Lecturas de demostración','Ensaya el vínculo etiqueta → recipiente → lote sin conectar hardware.')+`<div class="grid2"><section class="panel pad"><h2>Vincular etiqueta demo</h2><form id="v2-tag">${field('EPC / UID de prueba','<input name="epc" required maxlength="128" placeholder="TAG-DEMO-001">')}${field('Recipiente',`<select name="unit">${optsLots()}</select>`)}<button class="primary">Vincular etiqueta</button></form></section><section class="panel pad"><h2>Simular lectura</h2><form id="proto-reading">${field('Etiqueta vinculada','<input name="epc" required placeholder="TAG-DEMO-001">')}${field('Zona de lectura','<input name="zone" value="Punto de acopio demo" required>')}<button class="primary">Leer etiqueta demo</button></form><p>La lectura se registra en el histórico con origen simulado.</p></section></div><div class="actions spaced">${baseBtn('Tarjeta de empleado','nav:acceso')}${baseBtn('Básculas demo','nav:pesaje')}${protoButton('Guardar copia completa','backup')}</div><section class="panel pad"><h2>Lecturas registradas</h2>${state.v2.readings.slice(0,30).map(r=>`<div class="widget-row"><b>${esc(r.epc)}</b><span>${esc(r.unit||'Sin vincular')}<small>${esc(r.observedAt)}</small></span></div>`).join('')||'<p>Vincula una etiqueta y simula su primera lectura.</p>'}</section>`};
const protoIntegration=integrationView;integrationView=function(){return '<div class="notice">Demo autónoma: puedes importar/exportar ficheros. No se conecta a sistemas externos ni requiere configurar APIs.</div>'+protoIntegration().replace('Actualizar pasarela','Actualizar bandeja local')};
const protoRender=render;render=function(){protoRender();$('.top-actions .badge').textContent='DEMO AUTÓNOMA';if(!$('#proto-copy'))$('.top-actions').insertAdjacentHTML('beforeend','<button id="proto-copy" data-proto="about" aria-label="Copias y guía de la demo">'+ico('download')+'</button>')};
document.addEventListener('submit',e=>{if(e.target.id!=='proto-reading')return;e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{acceptReading({eventId:uid('DEMO-READ'),readerId:'LECTOR-DEMO',epc:d.epc,observedAt:new Date().toISOString(),zoneId:d.zone,source:'Simulación local',demo:true});persist();render();toast('Lectura demo registrada')}catch(e){toast(e.message)}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-proto]');if(!b)return;const a=b.dataset.proto;try{if(a==='about')about();if(a==='backup'){b.disabled=true;await saveRemote();if(syncDirty||syncBusy||syncConflict)throw Error('Hay cambios pendientes. Espera al guardado o resuelve el conflicto antes de copiar.');const data=await CuevaPrototype.backup();download('CUEVA_Copia_Demo_'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(data),'application/json');toast('Copia completa de registros y evidencias descargada')}if(a==='restore'){const file=$('#proto-restore-file').files[0];if(!file||!$('#proto-restore-confirm').checked)throw Error('Selecciona una copia y confirma el reemplazo');if(file.size>150*1024*1024)throw Error('Copia demasiado grande (máximo 150 MB)');if(syncBusy)throw Error('Espera a que termine el guardado actual');b.disabled=true;clearTimeout(syncTimer);syncReady=false;try{await CuevaPrototype.restore(JSON.parse(await file.text()));syncDirty=false;syncConflict=false;location.reload()}catch(err){syncReady=true;throw err}}}catch(e){toast(e.message)}finally{b.disabled=false}});
render();
